[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
journal = "D1e8th3BmrR3omMLYf2duJERyWH39ASiY9SEoWWTkCxp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/brimigs/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
